### ISSUE TITLE
A much bigger red button

### ISSUE THREAD

**Issue by andrewgilmartin** [xiaogdgenuine/Doll#18]
The application works as specified and I am grateful. I think it could better accentuate notifications by making the "Show notification as red badge" bigger, much bigger. For example,

![image](https://user-images.githubusercontent.com/19509/187267113-8dcee3f8-124c-47ee-82aa-1c43f8450da2.png)

I don't know if it possible for a menu bar item to break out of the boundaries of the menu bar, but if so this would be a useful enhancement.

**Comment by xiaogdgenuine** [comment]
@andrewgilmartin it's possible, take me sometime but here is a draft implementation:

<Video src='https://user-images.githubusercontent.com/51731239/211754148-9e5ab821-b75f-4c55-855b-e12726c6053e.mp4'></video>

I'm sure with this feature you won't miss any message :P!

Will release it in next version.

**Comment by andrewgilmartin** [comment]
Wow, that is noticeable! Looking forward to the additional. Thank you.

**Comment by xiaogdgenuine** [comment]
New version released, I endup with implement it as an arrow instead of a hollow circle, cause this way I don't need to care much about how menubar shifts between `normal/fullscreen` mode, to be honeset detect menubar shifts in macos is really hard, I haven't found a perfect way so far.

Anyway arraow seems fine, please try the new release and any feedback is welcome :P
https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.8
