### ISSUE TITLE
[Suggestion] Choose custom icon per app for menubar

### ISSUE THREAD

**Issue by marcharding** [xiaogdgenuine/Doll#19]
First of all, thank you so much for this app.  It was exactly what I was looking for!

Unfortunately, some of the icons in the menu bar look pretty terrible (hello ms teams) and I would really like to keep the menu bar in black and white (gray).

It would be great to add an option to add a custom icon for the menu bar for each monitored app.

(I'll try to add that myself, but I'm not familiar with Xcode and Swift, so that will probably take a while 🙃)

**Comment by aon** [comment]
I’d like to collaborate as well! @xiaogdgenuine is it ok to make a PR for a new feature like this one?

**Comment by xiaogdgenuine** [comment]
@aon This project is open source, always welcome PR, and since I'm not always got time to review them, please fork the repo and have fun your self first :P, I will come back to check from time to time.

@marcharding this is a good enhancement, it will take sometime to implement(some image processing works), but it's doable, I will take sometime to make it and release in next version.

**Comment by xiaogdgenuine** [comment]
New version released, please try it out @marcharding @aon 
https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.8

You can pick any image that macos support natively, even replace the image by just pick another `*.app` item, also you can reset the icon back to origin by re-pick the origin app in `Applications` folder.

Close the issue for now, re-open it if you have any further feedback/questions :P

**Comment by aon** [comment]
Works awesome! Thanks for this. Although I have to say in the last couple of months the color icons kinda grew in me 🙄
