### ISSUE TITLE
Cannot run doll v0.0.3

### ISSUE THREAD

**Issue by zachkont** [xiaogdgenuine/Doll#2]
<img width="252" alt="image" src="https://user-images.githubusercontent.com/17274058/154237414-b8066dbb-76e3-4edd-8bde-96689e5a8c91.png">

macOS Monterey  v12.2.1 M1 chip

**Comment by xiaogdgenuine** [comment]
This is expected, since I didn't sign the dmg file with a valid Apple developer certificate.

If you trust me, you can do:

_**System Preferences > Security > General > Open anyway**_

![image](https://user-images.githubusercontent.com/51731239/154404283-5186a224-a94b-40eb-bbfb-4924159b386e.png)

If you don't, you are welcome to download the code and compile the app yourself :P

**Comment by zachkont** [comment]
Thanks for helping me with this!
